# Generated by Django 2.2.5 on 2019-10-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='establishment_year',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pintrest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
