# Generated by Django 2.2.5 on 2019-10-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191026_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
