# Generated by Django 2.2.5 on 2019-09-19 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('picture_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('rating', models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)])),
                ('shares', models.IntegerField()),
                ('caption', models.TextField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dish')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant')),
            ],
        ),
    ]
