# Generated by Django 2.2.5 on 2019-10-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191024_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
